/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SensorWorkArea;

import Business.Organization.Organization;
import Business.Organization.WaterWorksOrganization;
import Business.Sensor.Sensor;
import Business.Sensor.WaterQualitySensor;
import Business.SensorData.SensorData;
import Business.SensorData.WaterQualitySensorData;
import Business.WorkQueue.WaterWorksWorkRequest;
import Business.WorkQueue.WorkRequest;
import EDU.purdue.cs.bloat.shrink.Main;
import com.sun.org.apache.xerces.internal.impl.dv.util.Base64;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author puneeth
 */
public class WaterQualitySensorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form WaterQualityWorkArea
     */
    private JPanel userProcessContainer;
    private WaterQualitySensor sensor;
    private Organization organization;
    private WaterWorksOrganization waterWorksOrganization;
    private String image;
    private int random;

    public WaterQualitySensorWorkArea(JPanel userProcessContainer, WaterQualitySensor sensor, Organization organization, WaterWorksOrganization waterWorksOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.sensor = sensor;
        this.organization = organization;
        this.waterWorksOrganization = waterWorksOrganization;
        image = readImage();
        random = 0;
        populateSensorData();
    }

    public void populateSensorData() {
        DefaultTableModel model = (DefaultTableModel) sensorDataTable.getModel();
        model.setRowCount(0);

        sensor.getSensorDataDirectory().getSensorDataList().stream().filter((wqsd) -> (wqsd instanceof WaterQualitySensorData)).map((wqsd) -> {
            Object[] row = new Object[3];
            row[0] = wqsd;
            row[1] = wqsd.getDataRecordedDate();
            row[2] = ((WaterQualitySensorData) wqsd).getLevelOfConcern();
            return row;
        }).forEach((row) -> {
            model.addRow(row);
        });

    }

    public String readImage() {
        BufferedImage img;
        String image = null;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            img = ImageIO.read(new File("noimage.jpg"));
            ImageIO.write(img, "jpg", baos);
            baos.flush();
            image = Base64.encode(baos.toByteArray());
            baos.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sensorDataTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        wqiJText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Water Quality Sensor Work Area");

        sensorDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "WQI", "TimeStamp", "Levels of Concern"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sensorDataTable);

        jButton1.setText("Generate Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Last Generated Water Quality Index:");

        wqiJText.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(wqiJText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel2)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wqiJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int randomWQI = 0;
        if (random < 6) {
            randomWQI = sensor.randomWQI(true);            
            random++;
            if (random == 5) {
                random = 0;
                randomWQI = sensor.randomWQI(false);                
            }
        }
        
        
        SensorData wqi = sensor.getSensorDataDirectory().addSensorData(Sensor.SensorType.Water);
        ((WaterQualitySensorData) wqi).setWaterQualityIndex(randomWQI);
        String levelOfWQI = ((WaterQualitySensorData) wqi).getLevelOfConcern();
        if (levelOfWQI.equals("Poor") || levelOfWQI.equals("Marginal")) {
            WorkRequest wwwr = new WaterWorksWorkRequest();
            waterWorksOrganization.getWorkQueue().getWorkRequestList().add(wwwr);
            organization.getWorkQueue().getWorkRequestList().add(wwwr);
            wwwr.setMessage(levelOfWQI);
            wwwr.setRequestDate(new Date());
            wwwr.setStatus("Sent");
//            wwwr.setHouse(sensor.getHouse());
            ((WaterWorksWorkRequest) wwwr).setImage(image);
            ((WaterWorksWorkRequest) wwwr).setType(WorkRequest.RequestType.Sensor);
            ((WaterWorksWorkRequest) wwwr).setOrganization(organization);
            wwwr.setSensorData(wqi);
            wwwr.setSensor(sensor);

        }
        wqiJText.setText(String.valueOf(randomWQI));
        populateSensorData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sensorDataTable;
    private javax.swing.JTextField wqiJText;
    // End of variables declaration//GEN-END:variables
}
