/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.WasteManagementWorkArea;

import Business.SensorData.WasteLevelSensorData;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WasteManagementWorkRequest;
import Business.WorkQueue.WorkRequest;
import EDU.purdue.cs.bloat.shrink.Main;
import com.sun.org.apache.xerces.internal.impl.dv.util.Base64;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author puneeth
 */
public class ViewSensorTypeWasteWorkRequestDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSensorTypeWasteWorkRequestDetailJPanel
     */
    private JPanel userProcessContainer;
    private WasteManagementWorkRequest workRequest;
    private UserAccount userAccount;

    public ViewSensorTypeWasteWorkRequestDetailJPanel(JPanel userProcessContainer, WasteManagementWorkRequest workRequest, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.workRequest = workRequest;
        this.userAccount = userAccount;

        imageLabel.setSize(200, 200);
        loadData();

    }

    public void loadData() {
        assignJButton.setEnabled(false);
        if (!(workRequest.getSensor() == null)) {
            wasteLevelJText.setText(String.valueOf(((WasteLevelSensorData) workRequest.getSensorData()).getWasteLevel()));
            levelJText.setText(((WasteLevelSensorData) workRequest.getSensorData()).getLevelOfConcern());
            organizationJText.setText(workRequest.getOrganization().toString());
            latitudeJText.setText(String.valueOf(workRequest.getSensor().getLatitude()));
            longitudeJText.setText(String.valueOf(workRequest.getSensor().getLongitude()));
            houseNoJText.setText(String.valueOf(workRequest.getSensor().getUserAccount().getEmployee().getHouse().getHouseNo()));
            streetNameJText.setText(workRequest.getSensor().getUserAccount().getEmployee().getHouse().getStreetName());
            cityNameJText.setText(workRequest.getSensor().getUserAccount().getEmployee().getHouse().getCityName());
            stateNameJText.setText(workRequest.getSensor().getUserAccount().getEmployee().getHouse().getStatename());
            zipcodeJText.setText(workRequest.getSensor().getUserAccount().getEmployee().getHouse().getZipcode());
        } else {
            wasteLevelJText.setText("NOT AVAILABLE");
            levelJText.setText("NOT AVAILABLE");
            organizationJText.setText("NOT AVAILABLE");
            latitudeJText.setText(String.valueOf(workRequest.getLatitude()));
            longitudeJText.setText(String.valueOf(workRequest.getLongitude()));
            houseNoJText.setText("NOT AVAILABLE");
            streetNameJText.setText("NOT AVAILABLE");
            cityNameJText.setText("NOT AVAILABLE");
            stateNameJText.setText("NOT AVAILABLE");
            zipcodeJText.setText("NOT AVAILABLE");
        }
//        latitudeJText.setText(String.valueOf(workRequest.getLatitude()));
//        longitudeJText.setText(String.valueOf(workRequest.getLongitude()));
        statusJText.setText(workRequest.getStatus());
        UserAccount.displayImage(imageLabel, workRequest.getImage(), this);
        if (workRequest.getStatus().equals("Sent")) {
            assignJButton.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        wasteLevelJText = new javax.swing.JTextField();
        organizationJText = new javax.swing.JTextField();
        statusJText = new javax.swing.JTextField();
        levelJText = new javax.swing.JTextField();
        assignJButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        latitudeJText = new javax.swing.JTextField();
        longitudeJText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        houseNoJText = new javax.swing.JTextField();
        streetNameJText = new javax.swing.JTextField();
        cityNameJText = new javax.swing.JTextField();
        stateNameJText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zipcodeJText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Work Request Details");

        jLabel2.setText("Waste Level Index:");

        jLabel3.setText("Organization:");

        jLabel5.setText("Status:");

        jLabel6.setText("Level of Concern:");

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wasteLevelJText.setEditable(false);
        wasteLevelJText.setEnabled(false);

        organizationJText.setEditable(false);
        organizationJText.setEnabled(false);

        statusJText.setEditable(false);
        statusJText.setEnabled(false);

        levelJText.setEditable(false);
        levelJText.setEnabled(false);

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        imageLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));

        jLabel7.setText("Longitude:");

        latitudeJText.setEditable(false);
        latitudeJText.setEnabled(false);

        longitudeJText.setEditable(false);
        longitudeJText.setEnabled(false);

        jLabel8.setText("Latitude:");

        houseNoJText.setEnabled(false);

        streetNameJText.setEnabled(false);

        cityNameJText.setEnabled(false);

        stateNameJText.setEnabled(false);

        jLabel4.setText("House No:");

        zipcodeJText.setEnabled(false);

        jLabel9.setText("Street Name:");

        jLabel10.setText("City Name:");

        jLabel11.setText("State Name:");

        jLabel12.setText("ZIP Code:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(longitudeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(latitudeJText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(levelJText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusJText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(organizationJText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wasteLevelJText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(streetNameJText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cityNameJText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stateNameJText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zipcodeJText)
                                    .addComponent(houseNoJText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assignJButton))))
                        .addGap(96, 96, 96)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(wasteLevelJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(organizationJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(statusJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(levelJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(longitudeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(latitudeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(houseNoJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(streetNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel10))
                            .addComponent(cityNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(stateNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(zipcodeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(assignJButton)
                                .addComponent(jButton1)))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        WasteManagementWorkerWorkAreaJPanel aqwwa = (WasteManagementWorkerWorkAreaJPanel) component;
        aqwwa.populateComboBox();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        // TODO add your handling code here:
        workRequest.setReceiver(userAccount);
        workRequest.setStatus("Pending");
        JOptionPane.showMessageDialog(ViewSensorTypeWasteWorkRequestDetailJPanel.this,
                "Work Request assigned to you successfully!",
                "Success!",
                JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_assignJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JTextField cityNameJText;
    private javax.swing.JTextField houseNoJText;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField latitudeJText;
    private javax.swing.JTextField levelJText;
    private javax.swing.JTextField longitudeJText;
    private javax.swing.JTextField organizationJText;
    private javax.swing.JTextField stateNameJText;
    private javax.swing.JTextField statusJText;
    private javax.swing.JTextField streetNameJText;
    private javax.swing.JTextField wasteLevelJText;
    private javax.swing.JTextField zipcodeJText;
    // End of variables declaration//GEN-END:variables
}
