/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HouseholderWorkArea;

import Business.Sensor.Sensor;
import Business.Sensor.Sensor.SensorType;

import Business.Sensor.SensorDirectory;
import Business.UserAccount.UserAccount;
import Business.Utils.MyStringVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static userInterface.HouseholderWorkArea.NewRequestJPanel.randomLat;
import static userInterface.HouseholderWorkArea.NewRequestJPanel.randomLong;

/**
 *
 * @author puneeth
 */
public class AddSensorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddSensorJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private SensorDirectory sensorDirectory;
    private double latitude;
    private double longitude;

    public AddSensorJPanel(JPanel userProcessContainer, UserAccount account, SensorDirectory sensorDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.sensorDirectory = sensorDirectory;
        populateTypeCombo();
        addVerifiers();
    }

    public void populateTypeCombo() {
        sensorTypeJCombo.removeAllItems();
        for (SensorType type : Sensor.SensorType.values()) {
            sensorTypeJCombo.addItem(type);
        }
    }

    private void addVerifiers() {

        InputVerifier stringVerifier = new MyStringVerifier();
        nameJText.setInputVerifier(stringVerifier);
        moreDetailsJText.setInputVerifier(stringVerifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sensorTypeJCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        moreDetailsJText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        latitudeJText = new javax.swing.JTextField();
        longitudeJText = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Sensor Name:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Add Sensor");

        jLabel3.setText("SensorType:");

        sensorTypeJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("More Details:");

        jButton1.setText("Add Sensor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Latitude:");

        jLabel6.setText("Logitude:");

        latitudeJText.setEnabled(false);
        latitudeJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudeJTextActionPerformed(evt);
            }
        });

        longitudeJText.setEnabled(false);

        jButton4.setText("Generate Longitude & Latitude");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameJText)
                                    .addComponent(sensorTypeJCombo, 0, 160, Short.MAX_VALUE)
                                    .addComponent(moreDetailsJText)
                                    .addComponent(latitudeJText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(longitudeJText)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(46, 46, 46)
                        .addComponent(jButton4)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sensorTypeJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(moreDetailsJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(latitudeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(longitudeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (checkBlankInput() == Boolean.TRUE) {
            SensorType type = (SensorType) sensorTypeJCombo.getSelectedItem();
            if (type == null) {
                JOptionPane.showMessageDialog(this, "Sensor Type cannot be empty!", " Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Sensor sensor = sensorDirectory.createAndAddSensor(type);
            String name = nameJText.getText();
            String moreDetails = moreDetailsJText.getText();
            double latitude = Double.parseDouble(latitudeJText.getText());
            double longitude = Double.parseDouble(longitudeJText.getText());

            sensor.setUserAccount(account);
            sensor.setName(name);
            sensor.setMoreDetails(moreDetails);
            //sensor.setHouse(account.getEmployee().getHouse());
            sensor.setLatitude(latitude);
            sensor.setLongitude(longitude);

            JOptionPane.showMessageDialog(AddSensorJPanel.this,
                    type.getValue() + " added successfully!",
                    "Success!",
                    JOptionPane.INFORMATION_MESSAGE);

            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter all values", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearFields() {
        nameJText.setText("");
        moreDetailsJText.setText("");
        longitudeJText.setText("");
        latitudeJText.setText("");

    }

    private Boolean checkBlankInput() {
        if (nameJText.getText().length() == 0
                || moreDetailsJText.getText().length() == 0
                || longitudeJText.getText().length() == 0
                || latitudeJText.getText().length() == 0) {
            return false;
        } else {
            return true;
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageSensorsWorkArea mswa = (ManageSensorsWorkArea) component;
        mswa.populateSensorTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void latitudeJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudeJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudeJTextActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        latitude = randomLat();
        longitude = randomLong();
        latitudeJText.setText(String.valueOf(latitude));
        longitudeJText.setText(String.valueOf(longitude));
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField latitudeJText;
    private javax.swing.JTextField longitudeJText;
    private javax.swing.JTextField moreDetailsJText;
    private javax.swing.JTextField nameJText;
    private javax.swing.JComboBox sensorTypeJCombo;
    // End of variables declaration//GEN-END:variables
}
